# Contains dependencies without specific verions
# run: conda env create -f environment.yml
name: samp-phase01
dependencies:
- h5py
- numpy
- pandas
- python=3
- scikit-learn
- scipy
- theano
- pip:
  - git+git://github.com/openml/openml-python.git
  - pymc3==3.1
