name: samp-phase2
channels:
- defaults
dependencies:
- cairo=1.14.8=0
- cycler=0.10.0=py27_0
- dbus=1.10.10=0
- expat=2.1.0=0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- functools32=3.2.3.2=py27_0
- glib=2.50.2=1
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- icu=54.1=0
- jpeg=9b=0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libiconv=1.14=0
- libpng=1.6.27=0
- libxcb=1.12=1
- libxml2=2.9.4=0
- matplotlib=2.0.0=np112py27_0
- mkl=2017.0.1=0
- mkl-service=1.1.2=py27_3
- numpy=1.12.0=py27_0
- openssl=1.0.2k=0
- pandas=0.19.2=np112py27_1
- patsy=0.4.1=py27_0
- pcre=8.39=1
- pip=9.0.1=py27_1
- pixman=0.34.0=0
- pycairo=1.10.0=py27_0
- pyparsing=2.1.4=py27_0
- pyqt=5.6.0=py27_2
- python=2.7.13=0
- python-dateutil=2.6.0=py27_0
- pytz=2016.10=py27_0
- qt=5.6.2=3
- readline=6.2=2
- scikit-learn=0.18.1=np112py27_1
- scipy=0.18.1=np112py27_1
- setuptools=27.2.0=py27_0
- sip=4.18=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- subprocess32=3.2.7=py27_0
- theano=0.8.2=py27_0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- xarray=0.9.6=py27_0
- zlib=1.2.8=3
- pip:
  - alabaster==0.7.9
  - babel==2.3.4
  - bleach==1.5.0
  - commonmark==0.5.4
  - configparser==3.5.0
  - decorator==4.0.11
  - docutils==0.13.1
  - entrypoints==0.2.2
  - enum34==1.1.6
  - h5py==2.7.1
  - html5lib==0.9999999
  - imagesize==0.7.1
  - ipython-genutils==0.1.0
  - jinja2==2.9.5
  - joblib==0.10.3
  - jsonschema==2.6.0
  - jupyter-core==4.3.0
  - markupsafe==0.23
  - mistune==0.7.3
  - nbconvert==5.1.1
  - nbformat==4.2.0
  - nbsphinx==0.2.13
  - numpydoc==0.6.0
  - pandocfilters==1.4.1
  - protobuf==3.2.0
  - pygments==2.2.0
  - pymc3==3.1
  - recommonmark==0.4.0
  - requests==2.13.0
  - snowballstemmer==1.2.1
  - sphinx==1.5.2
  - tensorflow-gpu==1.0.1
  - testpath==0.3
  - tqdm==4.11.2
  - traitlets==4.3.1
