name: SB_P3
channels:
- defaults
dependencies:
- certifi=2016.2.28=py27_0
- enum34=1.1.6=py27_0
- h5py=2.7.0=np112py27_0
- hdf5=1.8.17=2
- joblib=0.11=py27_0
- libgfortran=3.0.0=1
- libgpuarray=0.6.9=0
- mako=1.0.6=py27_0
- markupsafe=1.0=py27_0
- mkl=2017.0.3=0
- mkl-service=1.1.2=py27_3
- nose=1.3.7=py27_1
- numpy=1.12.0=py27_0
- openssl=1.0.2l=0
- pandas=0.19.2=np112py27_1
- patsy=0.4.1=py27_0
- pip=9.0.1=py27_1
- pygpu=0.6.9=py27_0
- python=2.7.13=0
- python-dateutil=2.6.1=py27_0
- pytz=2017.2=py27_0
- readline=6.2=2
- scikit-learn=0.18.1=np112py27_1
- scipy=0.18.1=np112py27_1
- setuptools=36.4.0=py27_1
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- theano=0.9.0=py27_0
- tk=8.5.18=0
- tqdm=4.15.0=py27_0
- wheel=0.29.0=py27_0
- zlib=1.2.11=0
- pip:
  - git+git://github.com/rdturnermtl/pymc3/tree/slicer_safe.git
  - git+git://github.com/clusterlib/clusterlib.git
  - emcee==2.2.1
  - protobuf==3.2.0
